// CONFIG
var PW = 'EHC2026';
var CLAUDE_KEY = '';
var CLIENT_ID = '';
var TENANT_ID = 'common';
var F = ['EHC / Eingangsrechnungen','EHC / Vertraege','EHC / Korrespondenz','EHC / Personal','EHC / Finanzen','EHC / OP-Dokumentation','Qodia / Allgemein','Qodia / Investoren','Qodia / Vertraege','Privat / Allgemein','Kein Anhang'];
var M = [];
var sel = null;
var accessToken = null;
var isLoadingAI = false;

function ds() { var d = new Date(); return String(d.getFullYear()).slice(2)+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'); }
function fn(m) { if(!m.ah)return null; var p=m.ah.split('.'); var e=p.pop(); return ds()+'_'+m.org+'_'+p.join('.')+'.'+e; }
function toast(s) { var t=document.getElementById('toast'); t.textContent=s; t.classList.add('show'); setTimeout(function(){t.classList.remove('show');},2200); }

function loadConfig() { CLIENT_ID=localStorage.getItem('ki_client_id')||''; TENANT_ID=localStorage.getItem('ki_tenant_id')||'common'; CLAUDE_KEY=localStorage.getItem('ki_claude_key')||''; }
function saveConfig() { var cid=document.getElementById('cfg_client_id').value.trim(); var tid=document.getElementById('cfg_tenant_id').value.trim()||'common'; var ck=document.getElementById('cfg_claude_key').value.trim(); if(!cid){toast('Client ID fehlt!');return;} if(!ck){toast('Claude Key fehlt!');return;} CLIENT_ID=cid;TENANT_ID=tid;CLAUDE_KEY=ck; localStorage.setItem('ki_client_id',cid); localStorage.setItem('ki_tenant_id',tid); localStorage.setItem('ki_claude_key',ck); document.getElementById('cfgmodal').style.display='none'; toast('Konfiguration gespeichert'); }
function openConfig() { document.getElementById('cfg_client_id').value=CLIENT_ID; document.getElementById('cfg_tenant_id').value=TENANT_ID; document.getElementById('cfg_claude_key').value=CLAUDE_KEY; document.getElementById('cfgmodal').style.display='flex'; }
function closeConfig() { document.getElementById('cfgmodal').style.display='none'; }

function login() { var pw=document.getElementById('pw').value; if(pw===PW){ sessionStorage.setItem('ki','1'); document.getElementById('loginpage').style.display='none'; document.getElementById('mainpage').style.display='flex'; init(); } else { document.getElementById('err').style.display='block'; document.getElementById('pw').value=''; } }
function logout() { sessionStorage.removeItem('ki'); accessToken=null; location.reload(); }

function connectMicrosoft() { if(!CLIENT_ID){openConfig();toast('Bitte zuerst Client ID eintragen');return;} var ru=window.location.origin+window.location.pathname; var sc=encodeURIComponent('https://graph.microsoft.com/Mail.Read https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/User.Read'); var url='https://login.microsoftonline.com/'+TENANT_ID+'/oauth2/v2.0/authorize?client_id='+CLIENT_ID+'&response_type=token&redirect_uri='+encodeURIComponent(ru)+'&scope='+sc+'&response_mode=fragment'; window.location.href=url; }
function disconnectMicrosoft() { accessToken=null; M=[]; sel=null; updateMsftButton(false); rs(); rd(); toast('Microsoft Konto getrennt'); }
function checkOAuthCallback() { var hash=window.location.hash; if(hash&&hash.includes('access_token=')){ var params={}; hash.slice(1).split('&').forEach(function(p){var kv=p.split('=');params[kv[0]]=decodeURIComponent(kv[1]||'');}); if(params.access_token){ accessToken=params.access_token; window.history.replaceState({},document.title,window.location.pathname); updateMsftButton(true); toast('Microsoft verbunden'); loadMailsFromGraph(); } } }
function updateMsftButton(c) { var btn=document.getElementById('msftbtn'); var disc=document.getElementById('msftdisc'); if(c){btn.style.display='none';disc.style.display='inline-block';}else{btn.style.display='inline-block';disc.style.display='none';} }

async function loadMailsFromGraph() { if(!accessToken){toast('Nicht verbunden');return;} var badge=document.getElementById('badge'); badge.textContent='Lade Mails...'; badge.style.color='#7dd3fc'; try { var res=await fetch('https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$top=25&$select=id,subject,from,receivedDateTime,bodyPreview,isRead,importance,body,hasAttachments&$orderby=receivedDateTime desc',{headers:{'Authorization':'Bearer '+accessToken}}); if(res.status===401){accessToken=null;updateMsftButton(false);toast('Token abgelaufen');return;} if(!res.ok)throw new Error('HTTP '+res.status); var data=await res.json(); var rawMails=data.value||[]; M=rawMails.map(function(m,i){ var from=m.from&&m.from.emailAddress?m.from.emailAddress:{}; var org=(from.name||from.address||'Unbekannt').replace(/[^a-zA-Z0-9]/g,'_'); return {id:m.id,from:from.address||'?',fromName:from.name||from.address||'?',org:org,subj:m.subject||'(kein Betreff)',t:formatMailDate(m.receivedDateTime),prio:'pm',pl:'Wird analysiert...',ak:'',bg:'',wt:'',at:'',or:'EHC / Korrespondenz',ah:m.hasAttachments?'Anhang.pdf':null,r:0,fb:'',d:false,isRead:m.isRead,bodyText:stripHtml(m.body?m.body.content:m.bodyPreview||''),bodyPreview:m.bodyPreview||'',_raw:m}; }); rs(); if(M.length>0){pick(M[0].id);} toast(M.length+' Mails geladen'); analyzeMailsWithClaude(); } catch(e){toast('Fehler: '+e.message); badge.textContent='Fehler'; badge.style.color='#f87171';} }

function formatMailDate(s) { if(!s)return''; var d=new Date(s); var now=new Date(); var diff=now-d; var od=86400000; if(diff<od&&d.getDate()===now.getDate())return d.toLocaleTimeString('de',{hour:'2-digit',minute:'2-digit'}); if(diff<2*od)return'Gestern'; if(diff<7*od)return['So','Mo','Di','Mi','Do','Fr','Sa'][d.getDay()]; return d.toLocaleDateString('de',{day:'2-digit',month:'2-digit'}); }
function stripHtml(h) { return h.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim().slice(0,3000); }

async function analyzeMailsWithClaude() { if(!CLAUDE_KEY||M.length===0)return; var previews=M.slice(0,10).map(function(m,i){return '['+i+'] Von: '+m.fromName+' <'+m.from+'>\nBetreff: '+m.subj+'\nVorschau: '+m.bodyPreview.slice(0,150);}).join('\n\n'); var prioMap={'Wichtig & Dringend':'pu','Wichtig':'pi','Muss gemacht werden':'pm','Nice to have':'pn','Nachhalten':'pf'}; try { var res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':CLAUDE_KEY,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:1500,messages:[{role:'user',content:'Analysiere diese E-Mails fuer eine medizinische Praxis (EHC Hernienchirurgie Hamburg). Antworte NUR mit JSON-Array.\nFormat:[{"index":0,"prio":"Wichtig & Dringend|Wichtig|Muss gemacht werden|Nice to have|Nachhalten","aktion":"kurz","begruendung":"kurz","weitere":"optional","ordner":"EHC / Eingangsrechnungen|EHC / Vertraege|EHC / Korrespondenz|EHC / Personal|EHC / Finanzen|Qodia / Allgemein|Qodia / Investoren|Kein Anhang"}]\n\nMails:\n'+previews}]})}); var d=await res.json(); var text=(d.content&&d.content[0]?d.content[0].text:'[]'); var cats=JSON.parse(text.replace(/```json|```/g,'').trim()); cats.forEach(function(c){var m=M[c.index];if(!m)return;m.pl=c.prio||'Muss gemacht werden';m.prio=prioMap[m.pl]||'pm';m.ak=c.aktion||'';m.bg=c.begruendung||'';m.wt=c.weitere||'';m.or=c.ordner||'EHC / Korrespondenz';}); rs();if(sel)rd();toast('KI-Analyse abgeschlossen'); } catch(e){console.warn('KI-Analyse fehlgeschlagen:',e);} }

async function generateReply(id) { if(!CLAUDE_KEY){toast('Claude Key fehlt');openConfig();return;} var m=M.find(function(x){return x.id===id;}); if(!m||isLoadingAI)return; isLoadingAI=true; var ta=document.getElementById('ta'+id); var btn=document.getElementById('aibtn'+id); if(btn){btn.textContent='Generiere...';btn.disabled=true;} if(ta){ta.value='';ta.placeholder='KI generiert Antwort...';} try { var res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':CLAUDE_KEY,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:500,messages:[{role:'user',content:'Schreibe eine professionelle deutsche Antwort. Unterschrift: "Mit freundlichen Gruessen\nOle Reinpold\nEHC Hamburg". Direkt starten.\n\nVon: '+m.fromName+' <'+m.from+'>\nBetreff: '+m.subj+'\n\nInhalt:\n'+(m.bodyText||m.bodyPreview)}]})}); var d=await res.json(); var reply=d.content&&d.content[0]?d.content[0].text:''; m.at=reply; if(ta){ta.value=reply;ta.placeholder='';} toast('Antwort generiert'); } catch(e){toast('KI-Fehler: '+e.message);} finally{isLoadingAI=false;if(btn){btn.textContent='KI Antwort';btn.disabled=false;}} }

async function markAsRead(id) { if(!accessToken)return; try{await fetch('https://graph.microsoft.com/v1.0/me/messages/'+id,{method:'PATCH',headers:{'Authorization':'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify({isRead:true})});}catch(e){} }
async function sendViaGraph(id) { if(!accessToken){toast('Nicht verbunden');return;} var m=M.find(function(x){return x.id===id;}); var ta=document.getElementById('ta'+id); if(!m||!ta)return; var body=ta.value; if(!body.trim()){toast('Antwort leer');return;} try{var res=await fetch('https://graph.microsoft.com/v1.0/me/messages/'+id+'/reply',{method:'POST',headers:{'Authorization':'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify({comment:body})}); if(res.ok){toast('Gesendet');m.isRead=true;}else{var err=await res.json();toast('Fehler: '+(err.error?err.error.message:res.status));}}catch(e){toast('Fehler: '+e.message);} }

function refreshMails() { if(accessToken){M=[];sel=null;rs();rd();loadMailsFromGraph();}else{toast('Bitte Microsoft verbinden');} }

function rs() { var p=M.filter(function(m){return!m.d;}).length; document.getElementById('badge').textContent=p+' ausstehend'; document.getElementById('badge').style.color='#fbbf24'; document.getElementById('sc').textContent=M.length; document.getElementById('slist').innerHTML=M.map(function(m){return '<div class="mr'+(m.d?' done':'')+(sel&&sel.id===m.id?' active':'')+(!m.isRead?' unread':'')+'" onclick="pick(\''+escId(m.id)+'\')"><div class="mt"><span class="prio '+m.prio+'">'+m.pl+'</span><span class="mtime">'+m.t+'</span></div><div class="msubj">'+escHtml(m.subj)+'</div><div class="mfrom">'+escHtml(m.fromName||m.from)+'</div></div>';}).join(''); }

function rd() { var det=document.getElementById('det'); if(!sel){det.innerHTML='<div class="empty"><span style="font-size:32px;opacity:0.15">@</span><span style="font-size:12px">Mail auswaehlen</span></div>';return;} var m=sel; var f=fn(m); var SL=['','Falsch','Eher falsch','Teilweise','Gut','Perfekt']; var h='<div class="dhead"><div class="dinfo"><div class="dsubj">'+escHtml(m.subj)+'</div><div class="dfrom">'+escHtml(m.fromName||m.from)+' &lt;'+escHtml(m.from)+'&gt; - '+m.t+'</div></div><span class="prio '+m.prio+'">'+m.pl+'</span></div>'; h+='<div class="dbody">'; h+='<div class="g3"><div><div class="lbl">Aktion</div><div class="card">'+escHtml(m.ak||'-')+'</div></div><div><div class="lbl">Begruendung</div><div class="card">'+escHtml(m.bg||'-')+'</div></div><div><div class="lbl">Weitere Aktionen</div><div class="card" style="color:#888">'+escHtml(m.wt||'-')+'</div></div></div>'; h+='<div><div class="lbl" style="display:flex;justify-content:space-between;align-items:center"><span>Antwortvorschlag</span><button class="btn" id="aibtn'+escId(m.id)+'" onclick="generateReply(\''+escId(m.id)+'\');" style="background:rgba(212,184,150,0.15);color:#d4b896;border:1px solid rgba(212,184,150,0.3);padding:3px 10px;font-size:10px">KI Antwort</button></div><textarea id="ta'+escId(m.id)+'" rows="9">'+escHtml(m.at)+'</textarea></div>'; h+='<div class="g2"><div><div class="lbl">OneDrive Ordner</div><select id="fs'+escId(m.id)+'">'+F.map(function(x){return'<option'+(x===m.or?' selected':'')+'>'+x+'</option>';}).join('')+'</select>'+(f?'<div class="fname"><span class="fnx">'+ds()+'_'+m.org+'_</span>'+m.ah+'</div>':'<div style="font-size:10px;color:#444;margin-top:5px">Kein Anhang</div>')+'</div>'; h+='<div class="fbbox"><div class="lbl">Feedback KI-Training</div><div class="stars">'+[1,2,3,4,5].map(function(i){return'<span class="star'+(i<=m.r?' on':'')+'" onclick="rate(\''+escId(m.id)+'\','+i+')" onmouseenter="hs(\''+escId(m.id)+'\','+i+')" onmouseleave="hs(\''+escId(m.id)+'\',0)">&#9733;</span>';}).join('')+'<span class="slbl" id="slbl'+escId(m.id)+'">'+(m.r?SL[m.r]:'')+'</span></div><textarea rows="3" placeholder="Was war falsch?" style="font-size:11px" id="fb'+escId(m.id)+'">'+escHtml(m.fb)+'</textarea></div></div></div>'; h+='<div class="dfoot"><button class="btn bconf" onclick="conf(\''+escId(m.id)+'\')">Bestaetigen</button>'+(accessToken?'<button class="btn bol" onclick="sendViaGraph(\''+escId(m.id)+'\')">Senden</button>':'<button class="btn bol" onclick="ol(\''+escId(m.id)+'\')">In Outlook</button>')+'<button class="btn bsave" onclick="save(\''+escId(m.id)+'\')">Entwurf</button><span class="sok" id="ok'+escId(m.id)+'">gespeichert</span><button class="btn bskip" onclick="skip(\''+escId(m.id)+'\')">Naechste</button></div>'; det.innerHTML=h; }

function pick(id) { sel=M.find(function(m){return m.id==id;}); if(sel&&!sel.isRead){markAsRead(sel.id);sel.isRead=true;} rs();rd(); }
function hs(id,n) { var m=M.find(function(x){return x.id==id;}); var L=['','Falsch','Eher falsch','Teilweise','Gut','Perfekt']; var l=document.getElementById('slbl'+id); if(l)l.textContent=n?L[n]:(m&&m.r?L[m.r]:''); }
function rate(id,r) { var m=M.find(function(x){return x.id==id;}); if(m)m.r=r; rd(); }
function save(id) { var m=M.find(function(x){return x.id==id;}); if(!m)return; var ta=document.getElementById('ta'+id),fb=document.getElementById('fb'+id),fs=document.getElementById('fs'+id); if(ta)m.at=ta.value;if(fb)m.fb=fb.value;if(fs)m.or=fs.value; var ok=document.getElementById('ok'+id); if(ok){ok.style.display='block';setTimeout(function(){ok.style.display='none';},2000);} }
function conf(id) { save(id); var m=M.find(function(x){return x.id==id;}); if(m)m.d=true; toast('Abgelegt'); sel=M.find(function(x){return!x.d;})||null; rs();rd(); }
function skip(id) { var i=M.findIndex(function(x){return x.id==id;}); sel=M.find(function(x,j){return j>i&&!x.d;})||M.find(function(x,j){return j<i&&!x.d;})||null; rs();rd(); }
function ol(id) { var m=M.find(function(x){return x.id==id;}); var ta=document.getElementById('ta'+id); window.open('mailto:'+m.from+'?subject='+encodeURIComponent('AW: '+m.subj)+'&body='+encodeURIComponent(ta?ta.value:m.at),'_self'); }
function escHtml(s) { return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
function escId(id) { return String(id).replace(/[^a-zA-Z0-9]/g,'_'); }

function init() { loadConfig(); checkOAuthCallback(); if(!accessToken&&M.length===0){ M=[{id:'d1',from:'rechnungen@helios-kliniken.de',fromName:'Helios Kliniken',org:'Helios_Kliniken',subj:'Rechnung Maerz 2026',t:'09:14',prio:'pu',pl:'Wichtig & Dringend',ak:'Rechnung pruefen und bezahlen',bg:'Zahlungsfrist 14 Tage.',wt:'Betrag pruefen.',at:'Sehr geehrte Damen und Herren,\n\ndie Zahlung veranlasse ich zeitnah.\n\nMit freundlichen Gruessen\nOle Reinpold',or:'EHC / Eingangsrechnungen',ah:'Rechnung_EHC_Maerz2026.pdf',r:0,fb:'',d:false,isRead:false,bodyText:'Demo',bodyPreview:'Rechnung Maerz 2026...'},{id:'d2',from:'k.mueller@praxis-mueller.de',fromName:'Praxis Mueller',org:'Praxis_Mueller',subj:'Patientenueberweisung Hernie',t:'10:32',prio:'pi',pl:'Wichtig',ak:'Terminvorschlaege senden',bg:'Kollegin wartet.',wt:'Termin anlegen.',at:'Sehr geehrte Frau Dr. Mueller,\n\nTerminvorschlaege:\n- Di 08.04. 10:00 Uhr\n- Do 10.04. 14:00 Uhr\n\nMit freundlichen Gruessen\nOle Reinpold',or:'EHC / Korrespondenz',ah:null,r:0,fb:'',d:false,isRead:false,bodyText:'Demo',bodyPreview:'Patientenueberweisung...'},{id:'d3',from:'info@steuerberater-franke.de',fromName:'Steuerberater Franke',org:'Steuerberater_Franke',subj:'Unterlagen Jahresabschluss 2025',t:'Gestern',prio:'pm',pl:'Muss gemacht werden',ak:'Unterlagen zusammenstellen',bg:'Zweite Erinnerung.',wt:'Kontoauszuege und Belege.',at:'Sehr geehrter Herr Franke,\n\nUnterlagen folgen bis Ende der Woche.\n\nMit freundlichen Gruessen\nOle Reinpold',or:'EHC / Finanzen',ah:null,r:0,fb:'',d:false,isRead:true,bodyText:'Demo',bodyPreview:'Jahresabschluss...'},{id:'d4',from:'news@medtech-messe.de',fromName:'MedTech Summit',org:'MedTech_Messe',subj:'MedTech Summit Hamburg 2026',t:'Gestern',prio:'pn',pl:'Nice to have',ak:'Kenntnisnahme',bg:'Newsletter.',wt:'Datum vormerken.',at:'',or:'Kein Anhang',ah:null,r:0,fb:'',d:false,isRead:true,bodyText:'Demo',bodyPreview:'MedTech Summit...'},{id:'d5',from:'lasse@qodia.de',fromName:'Lasse / Qodia',org:'Qodia',subj:'Update Investorengespraech',t:'Mo',prio:'pf',pl:'Nachhalten',ak:'Bestaetigung abwarten',bg:'Update Lasse.',wt:'Kalender pruefen.',at:'Hi Lasse, danke, passt. Ole',or:'Qodia / Investoren',ah:null,r:0,fb:'',d:false,isRead:true,bodyText:'Demo',bodyPreview:'Update Investorengespraech...'}]; rs();pick('d1'); } }

document.addEventListener('DOMContentLoaded',function(){ loadConfig(); var hash=window.location.hash; if(hash&&hash.includes('access_token=')){ sessionStorage.setItem('ki','1'); document.getElementById('loginpage').style.display='none'; document.getElementById('mainpage').style.display='flex'; init(); } else if(sessionStorage.getItem('ki')==='1'){ document.getElementById('loginpage').style.display='none'; document.getElementById('mainpage').style.display='flex'; init(); } });